config/routes.rb
Rails.application.routes.draw do
  resources :contacts_files, only: [:index, :new, :create, :show]

  resources :contacts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/contacts_file.rb
class ContactsFile < ApplicationRecord
  serialize :file_attributes_map, Hash
  serialize :file_errors, Hash

  enum status: [:on_hold, :processing, :failed, :finished]

  has_one_attached :csv_file
  belongs_to :user, inverse_of: :contacts_files

  scope :by_user, ->(user) { where(user_id: user.id) }
end

app/controllers/contacts_files_controller.rb
class ContactsFilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts_files = ContactsFile.by_user(current_user).order(:id).page params[:page]
  end

  def new
    @contacts_file = ContactsFile.new
  end

  def create
    @contacts_file = ContactsFile.new(contacts_file_params)
    @contacts_file.user = current_user
    @contacts_file.on_hold!

    respond_to do |format|
      if @contacts_file.save
        ContactsCsvProcessorJob.perform_later(@contacts_file.id)

        format.html { redirect_to @contacts_file, notice: "Contacts file was successfully saved." }
        format.json { render :show, status: :created, location: @contacts_file }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contacts_file.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @contacts_file = ContactsFile.find(params[:id])
  end

  private

  ATTR_MAP_KEYS = %i[name_column_index date_of_birth_column_index phone_column_index address_column_index credit_card_column_index email_column_index]

  def contacts_file_params
    params.require(:contacts_file).permit(:csv_file, file_attributes_map: ATTR_MAP_KEYS)
  end
end

app/helpers/contacts_files_helper.rb
module ContactsFilesHelper
end

app/views/contacts_files/index.html.erb
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Files</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <%= link_to "Upload", new_contacts_file_path(), class: "btn btn-sm btn-outline-secondary" %>
      </div>
    </div>
  </div>

  <div class="table-responsive">
    <% if @contacts_files.empty? %>
      <span>The list is empty</span>
    <% else %>
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th>ID</th>
            <th>Status</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @contacts_files.each do |file| %>
            <tr>
              <td><%= file.id %></td>
              <td><%= file.status.to_s.titleize.capitalize %></td>
              <% if file.csv_file.present? %>
                <td><%= link_to "Download", rails_blob_path(file.csv_file, disposition: "attachment") %></td>
              <% else %>
                <td><span>File not found.</span></td>
              <% end %>
              <td><%= link_to "Details", contacts_file_path(file) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</main>

app/views/contacts_files/new.html.erb
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">File</h1>
  </div>

  <div class="row">
    <div class="col-md-7 col-lg-8">
      <%= form_with(model: @contacts_file) do |f| %>
        <div class="d-grid gap-2 col-6 mx-auto">
          <label class="btn btn-warning">
            Select File
            <span style="display:none;">
              <%= f.file_field :csv_file, accept: "text/csv", multiple: false, required: true %>
            </span>
          </label>
        </div>

        <hr class="my-4">
        
        <h4 class="mb-3">File details</h4>

        <div class="row g-3 justify-content-start">
          <div class="col-auto">
            <%= f.label "Name column index", class: "col-form-label" %>
          </div>
          <div class="col-2">
            <%= f.number_field 'file_attributes_map[name_column_index]', min: 0, value: 0, class: "form-control", required: true %>
          </div>
        </div>

        <div class="row g-3 justify-content-start">
          <div class="col-auto">
            <%= f.label "Birthdate column index", class: "col-form-label" %>
          </div>
          <div class="col-2">
            <%= f.number_field 'file_attributes_map[date_of_birth_column_index]', min: 0, value: 1, class: "form-control", required: true %>
          </div>
        </div>

        <div class="row g-3 justify-content-start">
          <div class="col-auto">
            <%= f.label "Phone column index", class: "col-form-label" %>
          </div>
          <div class="col-2">
            <%= f.number_field 'file_attributes_map[phone_column_index]', min: 0, value: 2, class: "form-control", required: true %>
          </div>
        </div>

        <div class="row g-3 justify-content-start">
          <div class="col-auto">
            <%= f.label "Address column index", class: "col-form-label" %>
          </div>
          <div class="col-2">
            <%= f.number_field 'file_attributes_map[address_column_index]', min: 0, value: 3, class: "form-control", required: true %>
          </div>
        </div>

        <div class="row g-3 justify-content-start">
          <div class="col-auto">
            <%= f.label "Credit Card column index", class: "col-form-label" %>
          </div>
          <div class="col-2">
            <%= f.number_field 'file_attributes_map[credit_card_column_index]', min: 0, value: 4, class: "form-control", required: true %>
          </div>
        </div>

        <div class="row g-3 justify-content-start">
          <div class="col-auto">
            <%= f.label "Email column index", class: "col-form-label" %>
          </div>
          <div class="col-2">
            <%= f.number_field 'file_attributes_map[email_column_index]', min: 0, value: 5, class: "form-control", required: true %>
          </div>
        </div>

        <hr class="my-4">

        <%= f.submit "Save", class: "w-100 btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>
</main>

app/views/contacts_files/show.html.erb
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">File</h1>
  </div>

  <div class="row">
    <h4 class="mb-3">Info</h4>
    <div class="row g-3 justify-content-start">
      <div class="col-auto">
        <span><strong>File name:</strong></span>
      </div>
      <div class="col-2">
        <span><%= @contacts_file.csv_file.filename %></span>
      </div>
    </div>

    <div class="row g-3 justify-content-start">
      <div class="col-auto">
        <span><strong>Status:</strong></span>
      </div>
      <div class="col-2">
        <span><%= @contacts_file.status.to_s.titleize.capitalize %></span>
      </div>
    </div>

    <hr class="my-4">

    <h4 class="mb-3">Errors</h4>

    <% if @contacts_file.file_errors.keys.empty? %>
      <span>The error list is empty</span>
    <% else %>
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th>Line</th>
            <th>Errors</th>
          </tr>
        </thead>
        <tbody>
          <% @contacts_file.file_errors.each do |line, errors| %>
            <tr>
              <td><%= line %></td>
              <td><%= errors %></td>
            <tr>
          <% end %>
    <% end %>
  </div>
</main>