config/routes.rb
Rails.application.routes.draw do
  resources :contacts_files, only: [:index, :new, :create, :show]

  resources :contacts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/contact.rb
class Contact < ApplicationRecord
  attr_accessor :credit_card, :raw_birthdate

  belongs_to :user, inverse_of: :contacts

  validates :name, :email, :address, :telephone, :date_of_birth, :credit_card_franchise, presence: true
  validates_uniqueness_of :email, scope: :user_id, message: "user already has this email contact"

  validates :name, format: { with: /\A[a-zA-Z0-9\s\-]+\z/,
                   message: "name MUST not have special characters, EXCEPT '-'" }

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP,
                   message: "must have a valid email format" }

  validates :telephone, format: { with: /\A\(\+57\)(\s|-)[0-9]{3}(\s|-)[0-9]{3}(\s|-)[0-9]{2}(\s|-)[0-9]{2}\z/,
                   message: "must have a valid telephone format. Ex: (+57) 320 432 05 09 or (+57) 320-432-05-09" }

  validate :birthdate_format

  def credit_card=(credit_card_number)
    return if credit_card_number.nil?
    write_attribute(:credit_card_digest, digest_from_number(credit_card_number))
    write_attribute(:last_4_credit_card, credit_card_number[-4..-1])
    write_attribute(:credit_card_length, credit_card_number.length)
    write_attribute(:credit_card_franchise, CreditCardFranchise.by_number(credit_card_number))
  end

  def date_of_birth=(value)
    write_attribute(:date_of_birth, value)
    @raw_birthdate = value
  end

  def digest_from_number(credit_card_number)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost

    BCrypt::Password.create(credit_card_number, cost: cost)
  end

  private

  def birthdate_format
    if !date_of_birth_valid?
      errors.add :date_of_birth, "invalid date format. Date must be ISO 8601, formats: %Y%m%d or %F"
    end

  end

  def date_of_birth_valid?
    return false if @raw_birthdate.nil?

    Date._strptime(@raw_birthdate, '%Y%m%d').present? ||
    Date._strptime(@raw_birthdate, '%F').present?
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :date_of_birth, :telephone, :address, :credit_card, :credit_card_franchise, :email)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :credit_card %>
    <%= form.text_field :credit_card %>
  </div>

  <div class="field">
    <%= form.label :credit_card_franchise %>
    <%= form.text_field :credit_card_franchise %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Contacts</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <%= link_to 'New Contact', new_contact_path, class: "btn btn-sm btn-outline-secondary" %>
      </div>
    </div>
  </div>

  <div class="table-responsive">
    <% if @contacts.empty? %>
      <span>The list is empty</span>
    <% else %>
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th>Name</th>
            <th>Date of birth</th>
            <th>Telephone</th>
            <th>Address</th>
            <th>Credit card</th>
            <th>Credit card franchise</th>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <% @contacts.each do |contact| %>
            <tr>
              <td><%= contact.name %></td>
              <td><%= contact.date_of_birth.strftime("%Y %B %e") %></td>
              <td><%= contact.telephone %></td>
              <td><%= contact.address %></td>
              <td><%= contact.last_4_credit_card %></td>
              <td><%= contact.credit_card_franchise %></td>
              <td><%= contact.email %></td>
              <td><%= link_to 'Show', contact %></td>
              <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
              <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        <tbody>
        </tbody>
      </table>
    <% end %>
  </div>
</main>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @contact.date_of_birth %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @contact.telephone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Credit card:</strong>
  <%= @contact.credit_card %>
</p>

<p>
  <strong>Credit card franchise:</strong>
  <%= @contact.credit_card_franchise %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>