config/routes.rb
Rails.application.routes.draw do
  resources :contacts_files, only: [:index, :new, :create, :show]

  resources :contacts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Koombea</a>
  <button 
    class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
</header

app/views/layouts/_side_menu.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="flex-shrink-0 p-3">
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Contacts
        </button>
        <div class="collapse show" id="home-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li class="nav-item"><%= link_to "List", contacts_path(), class: "link-dark rounded" %></li>
            <li class="nav-item"><%= link_to "Files", contacts_files_path(), class: "link-dark rounded" %></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KoombeaContacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <div class="container-fluid">
      <div class="row">
        <%= render partial: "layouts/side_menu" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KoombeaContacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="form-signin">
    <% flash.each do |name, msg| %>
     <%= content_tag :div, msg, class: name %>
    <% end %>

    <%= yield %>
  </body>
</html>